apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "craft-cms.fullname" . }}
  labels:
    {{- include "craft-cms.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  ENVIRONMENT: {{ .environment | quote }}
  APP_ID: {{ .appId | quote }}
  SECURITY_KEY: {{ .securityKey | quote }}
  DB_DRIVER: pgsql
  DB_SERVER: {{ .db.server | quote }}
  DB_PORT: {{ .db.port | quote }}
  DB_DATABASE: {{ .db.database | quote }}
  DB_USER: {{ .db.user | quote}}
  DB_PASSWORD: {{ .db.password | quote }}
  DB_SCHEMA: {{ .db.schema | default "public" | quote }}
  DB_TABLE_PREFIX: {{ .db.tablePrefix | default "" | quote }}
  CP_TRIGGER: {{ .cpTrigger | default "admin" | quote }}
  PRIMARY_SITE_URL: {{ .siteUrl | quote }}
  {{- end }}