name: GAE Deploy
on:
  push:
    branches:
      - main
jobs:
  gae-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
          
    - id: deploy
      name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.gcp_credentials }}
        deliverables: app.yaml
        version: ${{ github.sha }}
        promote: false

    - id: echo-url
      name: Echo Version URL
      run: echo "${{ steps.deploy.outputs.url }}"