name: GAE Deploy
on:
  push:
    branches:
      - main
jobs:
  gae-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
          
    - id: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.gcp_credentials }}
        deliverables: app.yaml
        version: craft-${{ github.sha }}
        promote: false

    - id: test
      run: echo "${{ steps.deploy.outputs.url }}"