name: GAE Deploy
on:
  push:
    branches:
      - main
jobs:
  gae-deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.gcp_credentials }}